service: ubc-courses

provider:
  name: aws
  runtime: python3.6
  stage: prod
  region: us-west-2
  memorySize: 128
  apiGateway:
      shouldStartNameWithService: true

plugins:
  - serverless-wsgi

custom:
  pythonRequirements:
    dockerFile: ./Dockerfile
  wsgi:
    app: app.app
    packRequirements: false

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}
          cors: true